# https://github.com/Sher-Chowdhury/Kubernetes-Study-Guide/tree/16a7d1d763634b64631b2146bf6b16436917db0d/Section-08/16_StorageClass#custom-storageclasses
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: retained-volumes
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate